apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwa-deployment
  labels:
    app: mpowered-pwa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mpowered-pwa
  template:
    metadata:
      name: pwa-pod
      labels:
        app: mpowered-pwa
    spec:
      containers:
        - name: pwa-container
          image: docker.pkg.github.com/mpowered-health/mpowered-health-pwa/mpower-pwa:latest
      imagePullSecrets:
        - name: regcred
